dist: trusty
sudo: false
os: linux
dist: xenial
language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - librapidxml-dev
      - libcurl4-openssl-dev
    update: true

install:
  - examples/build.sh

script:
  - examples/tests/tests
