dist: trusty
sudo: false
os: linux
dist: xenial
language: cpp

addons:
  apt:
    packages:
      librapidxml-dev
      libcurl-dev
    update: true

install:
  - examples/build.sh

script:
  - examples/tests/tests
