dist: trusty
sudo: true
os: linux
dist: focal
language: cpp

before_install:
  - sudo apt-get -y install librapidxml-dev
  - sudo apt-get -y install libcurl-dev

addons:
  apt:
    update: true

install:
  - examples/build.sh

script:
  - examples/tests/tests
