dist: trusty
sudo: false
os: linux
dist: xenial
language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - librapidxml-dev
      - libcurl4-openssl-dev
      - g++-10.3
    update: true

env:
  - MATRIX_EVAL="CC=gcc-10.3 && CXX=g++-10.3"

install:
  - examples/build.sh

script:
  - examples/tests/build/tests
