dist: xenial
sudo: false
os: linux
language: cpp
compiler:
- clang
- gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - librapidxml-dev
    - libcurl4-openssl-dev
    - g++
    update: true
env:
  matrix:
  - MATRIX_EVAL="CC=gcc-10.3 && CXX=g++-10.3"
  global:
  - secure: YCojgtuI83saVuDpAluv8evMpuA1xe9CNK/UEDMfdAGnHqcdju63PRZeATO4gVr9Q0g82J/hSNtEpk+7PB++/BQZVWnuFs2U/MV0U1IwfRZfwl0rOCenG/qaENDx6DI/xgaXlqEt49106ijZyL2iJLtT4Ghwbzo5KYmr7LAj8P6YrRvC+ah2O7H4uGsxQZjU5TDeYnVat9aRyHQ+y/CPIi2IuSP7cPcMMc/TE3vNJeuQ/9evQBG6Q1LeSvpJhHhkc0Y/eC0r2+W3QtSzcUHhobfdi1hrjNT94kAfxGgeKB9ed/4Y7nZ9BTVuZ9eIiuMJ6QDMiVDi+U0qERl+7By3Wl01iun8TPucSwWbXYTTccGajnOzgTd3Ev+m7B7t9bhoa+DhxrWoapC+8FAmqxMFqNmtC9n0SdbKnq2kLo06axN88C6JQHiN9/ztwDmQG2Ftk5KllBni6B7RGmKQ6AKBbbzloTtPkUvsaJ4qXVQ2ohsedGIeHT/Qb2W3UEFw0KZwQLbPPmgI7MKCTnkLSmOt57P37V9uajEqoe3vgiTTay+zoZGDuJXt11GkMGL+i7mAFFnjha5c5nKQR0iLM9+C43Y0uRN8oH57pBURM6ryWdQDbQpGRNitSSd1DVDN+UilBQi0s1Q8d5ciBYi0u5tsapKoucZDnrxbv/acr9WuSGE=
  - secure: O6EmJKumZ+PajPr0qW67VbtcC91DV08GoCLZ2JB2VDE/8Nouzc2fKC74R0Mq/ZGLMZz1/MUT2PoEldefPGw0onotumpVqsy2U4fnmXLrAZQaSvkPnVL5zV0uoWKIh+SHE+NJFzdWF1l0t3fTZ9f83TzGE/CbybYUsCPz7a5pqUGeguLwnb6RW/Wpfrnr8x/LK5iq8BzMo2/kH4oZOZJU98IOP4LsETB/NuC2+9kPI8EzNUeI6so4RtlEAJQgLN0RD+Ga1hytu+r9mOriw0XSebrG5DwvqZRvfBF2PyxUpoYtzB2pI7/V6zS2Osej0+w3WK2kPLCtTsXxXhvKT8Qlpn4FpyIRhUS1iIgSJ2C+LXK+hZyb8bY68jTEuMl5AFegC0Un7m0K3UlIsqhjVJaId8XZKUThzUJE0hDZ4VEPPfv1B3S0emSs+Bgh1aEg50SklgbDNtF7LNJtNyhKlynHbWuTLIbYMg2v9ovU4vQX1kBbNCDGg79zo+FfoWT7IfiA1G58PliG5yCS0338nW1bfoG2V30Q0QRyBzJ9/T9gNU/DGvI3Q5cj/YHuH17j9dvsv64onhCtfETxdt89PkwMyhWaMkMZALdjlSukCrBXGQekgP+jfJ2wpni5A/kMZXOPmd6XQkqzckf7O3x/w8V3VcfJXVkopVnRnaytSPyg/u4=
install:
- "./examples/build.sh"
script:
- "./examples/tests/build/tests"
